# Semana 3-BrendaParra

In [7]:
import numpy as np
import ipyparallel as ipp
%matplotlib inline

In [8]:
c=ipp.Client()
c.ids

[0, 1, 2, 3]

In [9]:
c[0:2]

<DirectView [0, 1]>

In [10]:
c[1:3].apply_sync(lambda: "Hola clase de MCA")

['Hola clase de MCA', 'Hola clase de MCA']

In [12]:
c[0].map_sync(lambda x,y,z: x+y+z, [1],[2],[3])

[6]

In [13]:
c[0].map_sync(lambda x,y,z: x+y+z, range(10), range(10), range(10))

[0, 3, 6, 9, 12, 15, 18, 21, 24, 27]

In [16]:
c[:].apply_sync(lambda x,y,z: x+y+z, range(10), range(10), range(10))

[[0,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  0,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  0,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9],
 [0,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  0,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  0,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9],
 [0,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  0,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  0,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9],
 [0,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  0,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  0,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9]]

In [17]:
c[:].map_sync(lambda x,y,z: x+y+z, range(10), range(10), range(10))

[0, 3, 6, 9, 12, 15, 18, 21, 24, 27]

In [32]:
%%timeit #//graficar
x=2**17
for i in np.arange(int(x**0.5)+1):
     x%i

/Users/bparra/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:259: RuntimeWarning: divide by zero encountered in long_scalars


The slowest run took 8.48 times longer than the fastest. This could mean that an intermediate result is being cached.
10000 loops, best of 3: 73.8 µs per loop


In [43]:

%%timeit
x=2**4
for i in np.arange(int(x**0.5)+1)[2:]:
     x%i


The slowest run took 10.17 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 2.65 µs per loop


In [36]:
x=x=2**20
np.arange(int(x**0.5)+1)


array([   0,    1,    2, ..., 1022, 1023, 1024])

In [42]:
all?

In [ ]:
lambda x: all

In [ ]:
c[0].app

In [66]:
def PrimeQA(x):
    import numpy as np
    return all(x % i for i in np.arange(int(x**0.5)+1)[2:])

In [67]:
PrimeQ0(2**7)

False

In [68]:
c[0].apply_sync(PrimeQ0, 2**7) #se utiliza en un motor

False

In [69]:
dview = c[:] # asigna todos los motores a la variable dview

In [70]:
dview.apply_sync(PrimeQ0, 2**7)

[False, False, False, False]

In [73]:
2**np.arange(7)

array([ 1,  2,  4,  8, 16, 32, 64])

In [75]:
%timeit dview.map_sync(PrimeQA, 2**np.arange(25)) #Utiliza todos los motores con map_sync

10 loops, best of 3: 29.5 ms per loop


In [76]:
%%timeit
for i in np.arange(25):
    x%i

/Users/bparra/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:258: RuntimeWarning: divide by zero encountered in long_scalars


The slowest run took 81.98 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 8.61 µs per loop


In [89]:
def PrimeQB(x):
    import numpy as np
    return np.all(np.array([x % i for i in np.arange(np.int(x**0.5)+1)[2:]]))

In [90]:
np.all(np.array([x % i for i in np.arange(np.int(x**0.5)+1)[2:]]))

False

In [91]:
%timeit dview.map_sync(PrimeQB, 2**np.arange(25)) #Utiliza todos los motores con map_sync

10 loops, best of 3: 30.1 ms per loop


In [92]:
np.mod(24,12)

0

In [93]:
24%12

0

In [97]:
np.arange(24)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [104]:
for med in np.arange(12,20):
    print np.mod(np.arange(24),med) ## rehacer esto utilizando vista con map

[ 0  1  2  3  4  5  6  7  8  9 10 11  0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12  0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13  0  1  2  3  4  5  6  7  8  9]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14  0  1  2  3  4  5  6  7  8]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15  0  1  2  3  4  5  6  7]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16  0  1  2  3  4  5  6]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17  0  1  2  3  4  5]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18  0  1  2  3  4]


In [102]:
np.array([hora % 12 for hora in np.arange(24)]);

In [108]:
def PrimeQC(x):
    import numpy as np
    lista = np.arange(np.int(x**0.5)+1)[2:]
    residuos = np.mod(x,lista)
    return np.all(residuos)#np.array([x % i for i in np.arange(np.int(x**0.5)+1)[2:]]))

In [107]:
np.mod(12,np.arange(24)[2:])

array([ 0,  0,  0,  2,  0,  5,  4,  3,  2,  1,  0, 12, 12, 12, 12, 12, 12,
       12, 12, 12, 12, 12])

In [109]:
%timeit dview.map_sync(PrimeQB, 2**np.arange(10)) 
#Probar hasta 25 para ver su eficiencia contra PrimeQC

10 loops, best of 3: 31.4 ms per loop


In [110]:
%timeit dview.map_sync(PrimeQC, 2**np.arange(10))

10 loops, best of 3: 29.9 ms per loop
